service: voting-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:*
      Resource: "*"

functions:
  post-vote:
    handler: post-vote.postVote
    events:
      - http:
          path: vote
          method: post
  handle-votes:
    handler: handle-votes.handleSqsMessages
    events:
      - schedule: rate(2 minutes)