service: voting-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:*
      Resource: "*"

functions:
  post-vote:
    handler: handler.postVote
    events:
      - http:
          path: vote
          method: get